### ISSUE TITLE
Hairline Feature ?

### ISSUE THREAD

**Issue by m7mdcc** [Sapistudio/SeleniumStealth#1]
Thanks for your work ! 

Could you implment this detection ? 

https://intoli.com/blog/making-chrome-headless-undetectable/chrome-headless-test.html

**Comment by Sapistudio** [comment]
Hi.
for hairline fix,just use:
$driver = (new SeleniumStealth(driver))->usePhpWebriverClient()->fixHairline()->makeStealth();

**Comment by m7mdcc** [comment]
Thanks , It's work .

**Comment by m7mdcc** [comment]
@Sapistudio could you please change `protected function fixHairline()` to `public function fixHairline()`

**Comment by wysow** [comment]
@Sapistudio `fixHairline` is not a public function, is that on purpose?
